# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gpt',
                'doc_host': 'https://aaronsgithub.github.io',
                'git_url': 'https://github.com/aaronsgithub/gpt',
                'lib_path': 'gpt'},
  'syms': {'gpt.core': {'gpt.core.foo': ('core.html#foo', 'gpt/core.py')}}}
